# ç¼–è¯‘apk åŒæ—¶å‘å¸ƒåˆ°releaseé¡µé¢

name: flutter build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
    # è¿™ä¸ªä»»åŠ¡çš„æ­¥éª¤
    steps:
      # æ‹‰å–é¡¹ç›®ä»£ç 
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # å»ºç«‹ java ç¯å¢ƒ
      - name: ğŸ‰ Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - run: echo "ğŸ–¥ï¸ The java setup succeed."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      # å»ºç«‹  ç¯å¢ƒ
      - name: ğŸ§  Flutter action
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '2.x'
          channel: 'stable'
      - run: flutter --version
      - name:  ğŸ build apk
        run: |
          flutter pub get
          flutter build apk --release
      - run: echo "ğŸ’¡  build succeed."
      - name: ğŸ–¥ï¸ upload apk
        uses: actions/upload-artifact@v2.3.1
        with:
          name: app-preview
          path: build/app/outputs/apk/release/
      - run: echo "ğŸ‰ The job finish upload succeed."
      - run: ${{ steps.create_release.outputs.upload_url }}
      - name: Publish GitHub Release Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.dev_secret }}
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }} # ä¸Šä¼ ç½‘å€ï¼Œæ— éœ€æ”¹åŠ¨
          asset_path: build/outputs/apk/release/app-release.apk # ä¸Šä¼ è·¯å¾„
